version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: connect2job-backend
    restart: always
    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      NODE_ENV: development

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: connect2job-frontend
    restart: always
    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:5000/api

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

    stdin_open: true
    tty: true